### ISSUE TITLE
For Tensorflow 1.0?

### ISSUE THREAD

**Issue by softgearko** [RobRomijnders/ladder#6]
Hello.
I tried to run this code under tensorflow 1.0.
I got more than one error. 
The first one was came from tensorflow.python import control_flow_ops. I can fix it use tf.cond direct instead of control_flow_ops.
The second one is occurred at y_c, corrupted = encoder(inputs, noise_std) with;
```
Traceback (most recent call last):
  File "main.py", line 153, in <module>
    y_c, corrupted = encoder(inputs, noise_std)
  File "main.py", line 139, in encoder
    z = tf.cond(training, training_batch_norm, eval_batch_norm)
  File "/home/softgear/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1738, in cond
    orig_res, res_t = context_t.BuildCondBranch(fn1)
  File "/home/softgear/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1639, in BuildCondBranch
    r = fn()
  File "main.py", line 116, in training_batch_norm
    z = join(batch_normalization(z_pre_l), batch_normalization(z_pre_u, m, v))
  File "main.py", line 63, in <lambda>
    join = lambda l, u: tf.concat(0, [l, u])
  File "/home/softgear/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/softgear/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/home/softgear/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/softgear/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/softgear/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/softgear/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/softgear/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```
I don't know tensorflow 1.0 well.  I hope you fix this code for tensorflow 1.0. Thank you.

**Comment by RobRomijnders** [comment]
That's right. I wrote the code in TF0.10
